INSERT INTO PAISES (id, nome, nomept, sigla, bacen, indstatus, dtcadastro, dtedicao, dtexclusao, usucriou, usueditou, usuexcluiu) VALUES
(1,'Brazil','Brasil','BR',1058,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(2,'Afghanistan','Afeganistão','AF',132,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(3,'Albania','Albânia, Republica da','AL',175,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(4,'Algeria','Argélia','DZ',590,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(5,'American Samoa','Samoa Americana','AS',6912,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(6,'Andorra','Andorra','AD',370,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(7,'Angola','Angola','AO',400,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(8,'Anguilla','Anguilla','AI',418,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(9,'Antarctica','Antártida','AQ',3596,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(10,'Antigua and Barbuda','Antigua e Barbuda','AG',434,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(11,'Argentina','Argentina','AR',639,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(12,'Armenia','Armênia, Republica da','AM',647,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(13,'Aruba','Aruba','AW',655,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(14,'Australia','Austrália','AU',698,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(15,'Austria','Áustria','AT',728,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(16,'Azerbaijan','Azerbaijão, Republica do','AZ',736,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(17,'Bahamas','Bahamas, Ilhas','BS',779,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(18,'Bahrain','Bahrein, Ilhas','BH',809,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(19,'Bangladesh','Bangladesh','BD',817,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(20,'Barbados','Barbados','BB',833,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(21,'Belarus','Belarus, Republica da','BY',850,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(22,'Belgium','Bélgica','BE',876,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(23,'Belize','Belize','BZ',884,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(24,'Benin','Benin','BJ',2291,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(25,'Bermuda','Bermudas','BM',906,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(26,'Bhutan','Butão','BT',1198,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(27,'Bolivia','Bolívia','BO',973,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(28,'Bosnia and Herzegowina','Bósnia-herzegovina (Republica da','BA',981,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(29,'Botswana','Botsuana','BW',1015,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(30,'Bouvet Island','Bouvet, Ilha','BV',1023,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(31,'British Indian Ocean Territory','Território Britânico do Oceano Indico','IO',7820,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(32,'Brunei Darussalam','Brunei','BN',1082,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(33,'Bulgaria','Bulgária, Republica da','BG',1112,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(34,'Burkina Faso','Burkina Faso','BF',310,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(35,'Burundi','Burundi','BI',1155,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(36,'Cambodia','Camboja','KH',1414,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(37,'Cameroon','Camarões','CM',1457,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(38,'Canada','Canada','CA',1490,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(39,'Cape Verde','Cabo Verde, Republica de','CV',1279,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(40,'Cayman Islands','Cayman, Ilhas','KY',1376,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(41,'Central African Republic','Republica Centro-Africana','CF',6408,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(42,'Chad','Chade','TD',7889,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(43,'Chile','Chile','CL',1589,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(44,'China','China, Republica Popular','CN',1600,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(45,'Christmas Island','Christmas, Ilha (Navidad)','CX',5118,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(46,'Cocos (Keeling) Islands','Cocos (Keeling), Ilhas','CC',1651,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(47,'Colombia','Colômbia','CO',1694,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(48,'Comoros','Comores, Ilhas','KM',1732,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(49,'Congo','Congo','CG',1775,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(50,'Congo, the Democratic Republic of the','Congo, Republica Democrática do','CD',8885,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(51,'Cook Islands','Cook, Ilhas','CK',1830,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(52,'Costa Rica','Costa Rica','CR',1961,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(53,'Cote d`Ivoire','Costa do Marfim','CI',1937,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(54,'Croatia (Hrvatska)','Croácia (Republica da)','HR',1953,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(55,'Cuba','Cuba','CU',1996,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(56,'Cyprus','Chipre','CY',1635,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(57,'Czech Republic','Tcheca, Republica','CZ',7919,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(58,'Denmark','Dinamarca','DK',2321,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(59,'Djibouti','Djibuti','DJ',7838,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(60,'Dominica','Dominica, Ilha','DM',2356,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(61,'Dominican Republic','Republica Dominicana','DO',6475,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(62,'East Timor','Timor Leste','TL',7951,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(63,'Ecuador','Equador','EC',2399,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(64,'Egypt','Egito','EG',2402,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(65,'El Salvador','El Salvador','SV',6874,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(66,'Equatorial Guinea','Guine-Equatorial','GQ',3310,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(67,'Eritrea','Eritreia','ER',2437,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(68,'Estonia','Estônia, Republica da','EE',2518,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(69,'Ethiopia','Etiópia','ET',2534,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(70,'Falkland Islands (Malvinas)','Falkland (Ilhas Malvinas)','FK',2550,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(71,'Faroe Islands','Feroe, Ilhas','FO',2593,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(72,'Fiji','Fiji','FJ',8702,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(73,'Finland','Finlândia','FI',2712,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(74,'France','Franca','FR',2755,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(76,'French Guiana','Guiana francesa','GF',3255,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(77,'French Polynesia','Polinésia Francesa','PF',5991,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(78,'French Southern Territories','Terras Austrais e Antárticas Francesas','TF',3607,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(79,'Gabon','Gabão','GA',2810,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(80,'Gambia','Gambia','GM',2852,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(81,'Georgia','Georgia, Republica da','GE',2917,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(82,'Germany','Alemanha','DE',230,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(83,'Ghana','Gana','GH',2895,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(84,'Gibraltar','Gibraltar','GI',2933,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(85,'Greece','Grécia','GR',3018,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(86,'Greenland','Groenlândia','GL',3050,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(87,'Grenada','Granada','GD',2976,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(88,'Guadeloupe','Guadalupe','GP',3093,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(89,'Guam','Guam','GU',3131,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(90,'Guatemala','Guatemala','GT',3174,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(91,'Guinea','Guine','GN',3298,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(92,'Guinea-Bissau','Guine-Bissau','GW',3344,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(93,'Guyana','Guiana','GY',3379,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(94,'Haiti','Haiti','HT',3417,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(95,'Heard and Mc Donald Islands','Ilha Heard e Ilhas McDonald','HM',3603,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(96,'Holy See (Vatican City State)','Vaticano, Estado da Cidade do','VA',8486,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(97,'Honduras','Honduras','HN',3450,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(98,'Hong Kong','Hong Kong','HK',3514,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(99,'Hungary','Hungria, Republica da','HU',3557,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(100,'Iceland','Islândia','IS',3794,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(101,'India','Índia','IN',3611,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(102,'Indonesia','Indonésia','ID',3654,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(103,'Iran (Islamic Republic of)','Ira, Republica Islâmica do','IR',3727,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(104,'Iraq','Iraque','IQ',3697,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(105,'Ireland','Irlanda','IE',3751,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(106,'Israel','Israel','IL',3832,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(107,'Italy','Itália','IT',3867,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(108,'Jamaica','Jamaica','JM',3913,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(109,'Japan','Japão','JP',3999,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(110,'Jordan','Jordânia','JO',4030,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(111,'Kazakhstan','Cazaquistão, Republica do','KZ',1538,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(112,'Kenya','Quênia','KE',6238,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(113,'Kiribati','Kiribati','KI',4111,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(114,'Korea, Democratic People`s Republic of','Coreia, Republica Popular Democrática da','KP',1872,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(115,'Korea, Republic of','Coreia, Republica da','KR',1902,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(116,'Kuwait','Kuwait','KW',1988,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(117,'Kyrgyzstan','Quirguiz, Republica','KG',6254,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(118,'Lao People`s Democratic Republic','Laos, Republica Popular Democrática do','LA',4200,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(119,'Latvia','Letônia, Republica da','LV',4278,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(120,'Lebanon','Líbano','LB',4316,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(121,'Lesotho','Lesoto','LS',4260,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(122,'Liberia','Libéria','LR',4340,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(123,'Libyan Arab Jamahiriya','Líbia','LY',4383,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(124,'Liechtenstein','Liechtenstein','LI',4405,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(125,'Lithuania','Lituânia, Republica da','LT',4421,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(126,'Luxembourg','Luxemburgo','LU',4456,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(127,'Macau','Macau','MO',4472,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(128,'North Macedonia','Macedônia do Norte','MK',4499,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(129,'Madagascar','Madagascar','MG',4502,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(130,'Malawi','Malavi','MW',4588,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(131,'Malaysia','Malásia','MY',4553,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(132,'Maldives','Maldivas','MV',4618,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(133,'Mali','Mali','ML',4642,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(134,'Malta','Malta','MT',4677,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(135,'Marshall Islands','Marshall, Ilhas','MH',4766,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(136,'Martinique','Martinica','MQ',4774,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(137,'Mauritania','Mauritânia','MR',4880,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(138,'Mauritius','Mauricio','MU',4855,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(139,'Mayotte','Mayotte (Ilhas Francesas)','YT',4885,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(140,'Mexico','México','MX',4936,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(141,'Micronesia, Federated States of','Micronesia','FM',4995,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(142,'Moldova, Republic of','Moldávia, Republica da','MD',4944,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(143,'Monaco','Mônaco','MC',4952,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(144,'Mongolia','Mongólia','MN',4979,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(145,'Montserrat','Montserrat, Ilhas','MS',5010,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(146,'Morocco','Marrocos','MA',4740,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(147,'Mozambique','Moçambique','MZ',5053,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(148,'Myanmar','Mianmar (Birmânia)','MM',930,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(149,'Namibia','Namíbia','NA',5070,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(150,'Nauru','Nauru','NR',5088,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(151,'Nepal','Nepal','NP',5177,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(152,'Netherlands','Países Baixos (Holanda)','NL',5738,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(154,'New Caledonia','Nova Caledonia','NC',5428,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(155,'New Zealand','Nova Zelândia','NZ',5487,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(156,'Nicaragua','Nicarágua','NI',5215,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(157,'Niger','Níger','NE',5258,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(158,'Nigeria','Nigéria','NG',5282,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(159,'Niue','Niue, Ilha','NU',5312,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(160,'Norfolk Island','Norfolk, Ilha','NF',5355,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(161,'Northern Mariana Islands','Marianas do Norte','MP',4723,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(162,'Norway','Noruega','NO',5380,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(163,'Oman','Oma','OM',5568,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(164,'Pakistan','Paquistão','PK',5762,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(165,'Palau','Palau','PW',5754,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(166,'Panama','Panamá','PA',5800,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(167,'Papua New Guinea','Papua Nova Guine','PG',5452,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(168,'Paraguay','Paraguai','PY',5860,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(169,'Peru','Peru','PE',5894,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(170,'Philippines','Filipinas','PH',2674,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(171,'Pitcairn','Pitcairn, Ilha','PN',5932,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(172,'Poland','Polônia, Republica da','PL',6033,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(173,'Portugal','Portugal','PT',6076,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(174,'Puerto Rico','Porto Rico','PR',6114,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(175,'Qatar','Catar','QA',1546,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(176,'Reunion','Reunião, Ilha','RE',6602,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(177,'Romania','Romênia','RO',6700,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(178,'Russian Federation','Rússia, Federação da','RU',6769,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(179,'Rwanda','Ruanda','RW',6750,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(180,'Saint Kitts and Nevis','São Cristovão e Neves, Ilhas','KN',6955,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(181,'Saint LUCIA','Santa Lucia','LC',7153,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(182,'Saint Vincent and the Grenadines','São Vicente e Granadinas','VC',7056,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(183,'Samoa','Samoa','WS',6904,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(184,'San Marino','San Marino','SM',6971,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(185,'Sao Tome and Principe','São Tome e Príncipe, Ilhas','ST',7200,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(186,'Saudi Arabia','Arábia Saudita','SA',531,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(187,'Senegal','Senegal','SN',7285,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(188,'Seychelles','Seychelles','SC',7315,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(189,'Sierra Leone','Serra Leoa','SL',7358,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(190,'Singapore','Cingapura','SG',7412,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(191,'Slovakia (Slovak Republic)','Eslovaca, Republica','SK',2470,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(192,'Slovenia','Eslovênia, Republica da','SI',2461,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(193,'Solomon Islands','Salomão, Ilhas','SB',6777,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(194,'Somalia','Somalia','SO',7480,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(195,'South Africa','África do Sul','ZA',7560,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(196,'South Georgia and the South Sandwich Islands','Ilhas Geórgia do Sul e Sandwich do Sul','GS',2925,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(197,'Spain','Espanha','ES',2453,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(198,'Sri Lanka','Sri Lanka','LK',7501,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(199,'St. Helena','Santa Helena','SH',7102,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(200,'St. Pierre and Miquelon','São Pedro e Miquelon','PM',7005,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(201,'Sudan','Sudão','SD',7595,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(202,'Suriname','Suriname','SR',7706,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(203,'Svalbard and Jan Mayen Islands','Svalbard e Jan Mayen','SJ',7552,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(204,'Swaziland','Eswatini','SZ',7544,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(205,'Sweden','Suécia','SE',7641,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(206,'Switzerland','Suíça','CH',7676,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(207,'Syrian Arab Republic','Síria, Republica Árabe da','SY',7447,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(208,'Taiwan, Province of China','Formosa (Taiwan)','TW',1619,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(209,'Tajikistan','Tadjiquistao, Republica do','TJ',7722,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(210,'Tanzania, United Republic of','Tanzânia, Republica Unida da','TZ',7803,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(211,'Thailand','Tailândia','TH',7765,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(212,'Togo','Togo','TG',8001,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(213,'Tokelau','Toquelau, Ilhas','TK',8052,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(214,'Tonga','Tonga','TO',8109,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(215,'Trinidad and Tobago','Trinidad e Tobago','TT',8150,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(216,'Tunisia','Tunísia','TN',8206,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(217,'Turkey','Turquia','TR',8273,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(218,'Turkmenistan','Turcomenistão, Republica do','TM',8249,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(219,'Turks and Caicos Islands','Turcas e Caicos, Ilhas','TC',8230,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(220,'Tuvalu','Tuvalu','TV',8281,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(221,'Uganda','Uganda','UG',8338,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(222,'Ukraine','Ucrânia','UA',8311,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(223,'United Arab Emirates','Emirados Árabes Unidos','AE',2445,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(224,'United Kingdom','Reino Unido','GB',6289,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(225,'United States','Estados Unidos','US',2496,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(226,'United States Minor Outlying Islands','Ilhas Menores Distantes dos Estados Unidos','UM',18664,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(227,'Uruguay','Uruguai','UY',8451,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(228,'Uzbekistan','Uzbequistão, Republica do','UZ',8478,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(229,'Vanuatu','Vanuatu','VU',5517,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(230,'Venezuela','Venezuela','VE',8508,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(231,'Viet Nam','Vietnã','VN',8583,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(232,'Virgin Islands (British)','Virgens, Ilhas (Britânicas)','VG',8630,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(233,'Virgin Islands (U.S.)','Virgens, Ilhas (E.U.A.)','VI',8664,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(234,'Wallis and Futuna Islands','Wallis e Futuna, Ilhas','WF',8753,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(235,'Western Sahara','Saara Ocidental','EH',6858,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(236,'Yemen','Iémen','YE',3573,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(237,'Yugoslavia','Iugoslávia, República Fed. da','YU',3883,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(238,'Zambia','Zâmbia','ZM',8907,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(239,'Zimbabwe','Zimbabue','ZW',6653,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(240,'Bailiwick of Guernsey','Guernsey, Ilha do Canal (Inclui Alderney e Sark)','GG',1504,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(241,'Bailiwick of Jersey','Jersey, Ilha do Canal','JE',1508,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(243,'Isle of Man','Man, Ilha de','IM',3595,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(246,'Crna Gora (Montenegro)','Montenegro','ME',4985,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(247,'SÉRVIA','Republika Srbija','RS',7370,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(248,'Republic of South Sudan','Sudao do Sul','SS',7600,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(249,'Zona del Canal de Panamá','Zona do Canal do Panamá',NULL,8958,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(252,'Dawlat Filasṭīn','Palestina','PS',5780,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(253,'Åland Islands','Aland, Ilhas','AX',153,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(255,'Curaçao','Curaçao','CW',200,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(256,'Saint Martin','São Martinho, Ilha de (Parte Holandesa)','SM',6998,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(258,'Bonaire','Bonaire','AN',990,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(259,'Antartica','Antartica','AQ',420,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(260,'Heard Island and McDonald Islands','Ilha Herad e Ilhas Macdonald','AU',3433,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(261,'Saint-Barthélemy','São Bartolomeu','FR',6939,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(262,'Saint Martin','São Martinho, Ilha de (Parte Francesa)','SM',6980,'A',NULL,NULL,NULL,NULL,NULL,NULL),
(263,'Terres Australes et Antarctiques Françaises','Terras Austrais e Antárcticas Francesas','TF',7811,'A',NULL,NULL,NULL,NULL,NULL,NULL);
