CREATE TABLE USUARIOS (
  id int UNSIGNED NOT NULL AUTO_INCREMENT,
  idempresa int UNSIGNED NULL,
  tipopermissao varchar(1) NOT NULL,
  name varchar(100) NOT NULL,
  cpf varchar(11) UNIQUE NOT NULL,
  dtnascimento DATE NOT NULL,
  estadocivil varchar(2) NOT NULL,
  genero varchar(1) NOT NULL,
  indportadordeficiencia varchar(1) NOT NULL,
  email varchar(100) UNIQUE NOT NULL,
  telefonecelular varchar(20) UNIQUE NOT NULL,
  telefonefixo varchar(20) NULL,
  indviagem varchar(1) NOT NULL,
  indmudarcidade varchar(1) NOT NULL,
  indcelwhatsapp varchar(1) NOT NULL,
  indrecebermsg varchar(1) NOT NULL,
  urlfotoanexo varchar(2048) NOT NULL,
  tipoforca varchar(1) NOT NULL,
  indoficial varchar(1) NOT NULL,
  nrcertificado varchar(40) NOT NULL,
  urlcertificadoanexo varchar(2048) NOT NULL,
  postograduacao varchar(4) NOT NULL,
  nomeguerra varchar(100) NOT NULL,
  nomeultimobtl varchar(100) NOT NULL,
  idlogradouro int UNSIGNED NULL,
  resumoprofissional varchar(1024) NOT NULL,
  urllinkedin varchar(512) NULL,
  urlfacebook varchar(512) NULL,
  urlinstagram varchar(512) NULL,
  urltwitter varchar(512) NULL,
  urlyoutube varchar(512) NULL,
  urlblogsite varchar(512) NULL,
  dtverificacaoemail TIMESTAMP NULL,
  password varchar(255) NOT NULL,
  indstatus varchar(1) NOT NULL,
  dtcadastro TIMESTAMP NULL,
  dtedicao TIMESTAMP NULL,
  dtexclusao TIMESTAMP,
  usucriou int NULL,
  usueditou int NULL,
  usuexcluiu int NULL,
  PRIMARY KEY (id)
);

ALTER TABLE `USUARIOS` ADD CONSTRAINT `FK_EMPRESA` FOREIGN KEY (`idempresa`) REFERENCES `EMPRESAS` (`id`);
