CREATE TABLE failed_jobs (
  id int UNSIGNED NOT NULL AUTO_INCREMENT,
  connection TEXT NOT NULL,
  queue TEXT NOT NULL,
  payload LONGTEXT NOT NULL,
  exception LONGTEXT NOT NULL,
  failed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
  PRIMARY KEY (id)
);
