DROP TABLE IDIOMAS;
DROP TABLE ESPECIALIZACOES;
DROP TABLE NIVEIS_ESTUDO;
DROP TABLE AREAS_ATUACAO;
DROP TABLE NIVEIS_HIERARQUICOS;
DROP TABLE LOGRADOUROS;
DROP TABLE ESTADOS;
DROP TABLE CIDADES;
DROP TABLE PAISES;


